[build]
  environment = { YARN_VERSION = "1.21.1", APP_ENV = "development" }
  command = "yarn build"
  publish = "public/"
  functions = "functions"

[context.production]
  environment = { APP_ENV = "production" }

[[redirects]]
  from = "https://karimadelli.netlify.com"
  to = "https://karimadelli.fr/"
  status = 301

[[redirects]]
  from = "https://karimadelli.netlify.com/*"
  to = "https://karimadelli.fr/:splat"
  status = 301

[[redirects]]
  from = "https://www.karimadelli.fr"
  to = "https://karimadelli.fr/"
  status = 301

[[redirects]]
  from = "https://www.karimadelli.fr/*"
  to = "https://karimadelli.fr/:splat"
  status = 301

[[redirects]]
  from = "https://www.karimadelli.com"
  to = "https://karimadelli.fr/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.karimadelli.com/*"
  to = "https://karimadelli.fr/:splat"
  status = 301 
  force = true 

[[redirects]]
  from = "https://karimadelli.com"
  to = "https://karimadelli.fr/"
  status = 301
  force = true

[[redirects]]
  from = "https://karimadelli.com/*"
  to = "https://karimadelli.fr/:splat"
  status = 301  
  force = true

[[redirects]]
  from = "https://www.karimadelli.eu"
  to = "https://karimadelli.fr/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.karimadelli.eu/*"
  to = "https://karimadelli.fr/:splat"
  status = 301  
  force = true

[[redirects]]
  from = "https://karimadelli.eu"
  to = "https://karimadelli.fr/"
  status = 301
  force = true

[[redirects]]
  from = "https://karimadelli.eu/*"
  to = "https://karimadelli.fr/:splat"
  status = 301
  force = true

[[plugins]]
  package = "netlify-plugin-gatsby-cache"  